# Generated by Django 5.2.4 on 2025-07-23 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('objet', models.TextField()),
                ('num_ordre', models.CharField(max_length=50, unique=True)),
                ('courrier_scanné', models.FileField(upload_to='courriers/sortants/')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.service')),
            ],
        ),
        migrations.CreateModel(
            name='CourrierEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expediteur', models.CharField(max_length=255)),
                ('objet', models.TextField()),
                ('num_ordre', models.CharField(max_length=50, unique=True)),
                ('courrier_scanné', models.FileField(upload_to='courriers/entrants/')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.service')),
            ],
        ),
    ]
