# Generated by Django 5.2.7 on 2025-10-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0002_service_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierentrant',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
    ]
