# Generated by Django 5.2.7 on 2025-10-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0003_courrierentrant_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrierentrant',
            name='service',
        ),
        migrations.AddField(
            model_name='courrierentrant',
            name='services',
            field=models.ManyToManyField(blank=True, to='courriers.service', verbose_name='Services'),
        ),
    ]
