# Generated by Django 5.2.7 on 2025-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0004_remove_courrierentrant_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courriersortant',
            name='service',
        ),
        migrations.AddField(
            model_name='courriersortant',
            name='services',
            field=models.ManyToManyField(blank=True, to='courriers.service', verbose_name='Services'),
        ),
    ]
